Improvements
Signed-off-by: p-wysocki <przemyslaw.wysocki@intel.com>

diff --git a/src/bindings/python/scripts/stub_generation_precommit.yaml b/src/bindings/python/scripts/stub_generation_precommit.yaml
--- a/src/bindings/python/scripts/stub_generation_precommit.yaml
+++ b/src/bindings/python/scripts/stub_generation_precommit.yaml
@@ -10,6 +10,10 @@ repos:
           else
             "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/src/bindings/python/scripts/generate_pyapi_stubs.sh";
           fi;
+          if [ $? -ne 0 ]; then
+            echo "Stub generation failed. Aborting commit.";
+            exit 1;
+          fi;
           git add ./*.pyi'
         files: .*src/bindings/python/.*
         pass_filenames: false
